create table if not exists products (
    id bigint generated by default as identity primary key,
    source text not null default 'rebrickable',
    item_type text not null default 'SET',
    item_no text not null,
    name text,
    year integer,
    theme_id integer,
    num_parts integer,
    image_url text,
    created_at timestamptz not null default now(),
    unique(source, item_type, item_no)
);

create table if not exists market_valuations (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete cascade,
    marketplace text not null,
    condition text not null check (condition in ('N','U')),
    currency_code text not null default 'EUR',
    guide_type text,
    sales_count integer,
    min_price numeric(12,2),
    avg_price numeric(12,2),
    qty_avg_price numeric(12,2),
    median_price numeric(12,2),
    p25_price numeric(12,2),
    conservative_value numeric(12,2),
    confidence numeric(5,4),
    raw_json jsonb,
    observed_at timestamptz not null default now()
);

create table if not exists listings (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete set null,
    marketplace text not null,
    external_id text,
    title text,
    source_url text,
    seller_name text,
    location text,
    condition_text text,
    asking_price numeric(12,2) not null,
    shipping_price numeric(12,2) default 0,
    currency_code text not null default 'EUR',
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    is_active boolean not null default true,
    unique(marketplace, external_id)
);

create table if not exists listing_snapshots (
    id bigint generated by default as identity primary key,
    listing_id bigint references listings(id) on delete cascade,
    asking_price numeric(12,2),
    shipping_price numeric(12,2),
    is_active boolean,
    observed_at timestamptz not null default now()
);

create table if not exists opportunities (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete cascade,
    listing_id bigint references listings(id) on delete set null,
    source_marketplace text,
    source_url text,
    purchase_price numeric(12,2) not null,
    expected_sale_price numeric(12,2),
    selling_fees numeric(12,2),
    shipping_cost numeric(12,2),
    packaging_cost numeric(12,2),
    other_costs numeric(12,2),
    expected_profit numeric(12,2),
    expected_roi numeric(10,4),
    confidence numeric(5,4),
    liquidity_score numeric(5,4),
    score numeric(6,2),
    decision text,
    status text not null default 'OPEN',
    created_at timestamptz not null default now()
);

create table if not exists paper_trades (
    id bigint generated by default as identity primary key,
    opportunity_id bigint references opportunities(id) on delete cascade,
    simulated_purchase_price numeric(12,2) not null,
    simulated_sale_price numeric(12,2),
    expected_profit numeric(12,2),
    expected_roi numeric(10,4),
    outcome text default 'OPEN',
    notes text,
    opened_at timestamptz not null default now(),
    closed_at timestamptz
);

create table if not exists lot_analyses (
    id bigint generated by default as identity primary key,
    source_marketplace text,
    source_url text,
    asking_price numeric(12,2) not null,
    estimated_total_value numeric(12,2),
    estimated_costs numeric(12,2),
    expected_profit numeric(12,2),
    expected_roi numeric(10,4),
    confidence numeric(5,4),
    score numeric(6,2),
    decision text,
    created_at timestamptz not null default now()
);

create table if not exists lot_items (
    id bigint generated by default as identity primary key,
    lot_analysis_id bigint references lot_analyses(id) on delete cascade,
    product_id bigint references products(id) on delete set null,
    item_no text,
    quantity integer not null default 1,
    estimated_unit_value numeric(12,2),
    completeness_factor numeric(5,4) default 1.0,
    notes text
);

create index if not exists idx_products_item_no on products(item_no);
create index if not exists idx_market_valuations_product_observed on market_valuations(product_id, observed_at desc);
create index if not exists idx_listings_product_active on listings(product_id, is_active);
create index if not exists idx_opportunities_score on opportunities(score desc);
create index if not exists idx_paper_trades_outcome on paper_trades(outcome);
